<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="chassis_length" value="0.6"/>
    <xacro:property name="chassis_width" value="0.4"/>
    <xacro:property name="chassis_height" value="0.3"/>
    
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    
    <xacro:property name="wheel_base" value="0.38"/>   
    <xacro:property name="track_width" value="0.48"/>
    
    <xacro:property name="chassis_mass" value="20.0"/>
    <xacro:property name="wheel_mass" value="1.0"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>
    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <link name="base_link"></link>

    <joint name="base_frootprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="base_footprint"></link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_base/2} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0.197 0 0.078" rpy="0 0 ${-pi/2}"/> 
            <geometry>
                <mesh filename="package://robot2t/meshes/chassis.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <mass value="${chassis_mass}"/>
            <inertia ixx="${(1/12) * chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height)}" iyz="0.0"
                     izz="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width)}" />
        </inertial>
    </link>

   <xacro:macro name="rear_wheel" params="prefix y_offset">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 ${-pi/2} 0"/>
                <geometry>
                    <mesh filename="package://robot2t/meshes/wheels.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius - 0.005}" length="${wheel_thickness - 0.005}"/>
                </geometry>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.9</mu>
                            <mu2>0.9</mu2>
                        </ode>
                    </friction>
                </surface>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0" ixz="0"
                         iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0"
                         izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="chassis"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${y_offset} 0" rpy="${-pi/2} 0 0 "/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <xacro:rear_wheel prefix="left_rear" y_offset="${track_width/2}"/>
    <xacro:rear_wheel prefix="right_rear" y_offset="${-track_width/2}"/>

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * mass * (x*x + z*z)}" iyz="0.0"
                     izz="${(1/12) * mass * (x*x + y*y)}" />
        </inertial>
    </xacro:macro>

   <xacro:macro name="front_steering_wheel" params="prefix y_offset">
        
       <link name="${prefix}_steering_link">
        <visual>
             <geometry><box size="0.05 0.05 0.05"/></geometry> 
        </visual>
        
        <xacro:inertial_box mass="1.0" x="0.05" y="0.05" z="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="chassis"/>
            <child link="${prefix}_steering_link"/>
            <origin xyz="${wheel_base-0.008} ${y_offset} 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/> 
            <limit lower="-0.6" upper="0.6" effort="10" velocity="1.0"/>
        </joint>

        <link name="${prefix}_front_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 ${-pi/2} 0"/>
                <geometry>
                     <mesh filename="package://robot2t/meshes/wheels.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius - 0.005}" length="${wheel_thickness - 0.005}"/>
                </geometry>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.9</mu>
                            <mu2>0.9</mu2>
                        </ode>
                    </friction>
                </surface>
            </collision>
            
             <inertial>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0" ixz="0"
                         iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0"
                         izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
            </inertial>
        </link>

        <joint name="${prefix}_front_wheel_joint" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_front_wheel"/>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/> 
        </joint>

    </xacro:macro>

    <xacro:front_steering_wheel prefix="left_front" y_offset="${track_width/2}"/>
    <xacro:front_steering_wheel prefix="right_front" y_offset="${-track_width/2}"/>
                                                      
</robot>